version: '2.1'
services:
  vinyl:
    build:
      context: .
      dockerfile: docker/vinyl/Dockerfile
    ports:
      - 8080:8080
    environment:
      HOST: docker
    networks: [main]

  #TODO: wait on prisma healthcheck
  turntable-deploy:
    image: openrecord/turntable:prisma-cli
    depends_on: [prisma]
    command: npx prisma deploy
    environment:
      ENDPOINT: http://prisma:4466
    networks: [main]

  #TODO: Add healthcheck
  prisma:
    image: prismagraphql/prisma:1.15
    restart: always
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
    depends_on: [postgres]
    networks: [main]

  #TODO: Add healthcheck
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    networks: [main]

  chrome-headless:
    image: openrecord/chrome-headless
    build:
      dockerfile: docker/chrome-headless/Dockerfile
      context: .
    ports:
      - 9222:9222
    networks: [main]

networks:
  main:
    driver: bridge
