schemaPath: ./schema.graphql
extensions:
  endpoints:
    default: ${env:ENDPOINT}
  codegen:
    - generator: prisma-binding
      language: typescript
      output:
        binding: generated/prisma.ts
