api:
  port: API_PORT

puppeteer:
  headless:
    __name: PUPPETEER_HEADLESS
    __format: json # parse as a boolean
  useRemoteChrome:
    __name: PUPPETEER_USE_REMOTE_CHROME
    __format: json # parse as a boolean
  remoteChromeEndpoint: PUPPETEER_REMOTE_CHROME_ENDPOINT
  baseUrl: PUPPETEER_BASEURL
  slowMoMillis: PUPPETEER_SLOW_MILLIS
